import 'package:flutter/material.dart';

import '../services/locale_service.dart';

class AppStrings {
  AppStrings._(this.language);

  final AppLanguage language;

  static AppStrings of(AppLanguage language) => AppStrings._(language);

  static AppStrings get current => AppStrings.of(LocaleService.instance.language);

  static const Map<AppLanguage, Map<String, String>> _values = {
    AppLanguage.spanish: {
      'appName': 'FarmaDose',
      'language': 'Idioma',
      'spanishLatam': 'Español LATAM',
      'portugueseBrazil': 'Português Brasil',
      'loading': 'Cargando...',
      'close': 'Cerrar',
      'save': 'Guardar',
      'landingBadge': 'Suscripción médica para LATAM',
      'landingHeadline': 'FarmaDose',
      'landingSubtitle':
          'Calcula, analiza y verifica dosis de medicamentos con apoyo de IA, fuentes oficiales y explicación detallada.',
      'startNow': 'Comenzar ahora',
      'login': 'Iniciar sesión',
      'landingHeroTitle': 'Diseñado para decisiones más claras y seguras',
      'landingHeroStat1Title': 'IA + criterio clínico',
      'landingHeroStat1Description':
          'Explicaciones útiles en español para equipos LATAM.',
      'landingHeroStat2Title': 'Fuentes verificables',
      'landingHeroStat2Description':
          'Consulta la base oficial seleccionada antes de decidir.',
      'landingHeroStat3Title': 'Alertas automáticas',
      'landingHeroStat3Description':
          'Identifica inconsistencias y errores potenciales al instante.',
      'benefits': 'Beneficios',
      'benefit1': 'Cálculo detallado paso a paso',
      'benefit2': 'Fuentes oficiales verificables',
      'benefit3': 'Sugerencias inteligentes si escribes mal el medicamento',
      'benefit4': 'Alertas automáticas de seguridad',
      'benefit5': 'Explicaciones en español para LATAM',
      'howItWorks': 'Cómo funciona',
      'step1': 'Ingresa el medicamento',
      'step2': 'Agrega los datos del paciente',
      'step3': 'Selecciona la fuente oficial',
      'step4': 'Revisa el cálculo y la explicación',
      'plans': 'Planes',
      'monthlyPlan': 'Plan mensual',
      'annualPlan': 'Plan anual',
      'bestPrice': 'Mejor precio',
      'fullAccess': 'Acceso completo',
      'updatesIncluded': 'Actualizaciones incluidas',
      'chooseMonthlyPlan': 'Elegir plan mensual',
      'chooseAnnualPlan': 'Elegir plan anual',
      'monthlyPriceLabel': '\$6.90 USD / mes',
      'annualPriceLabel': '\$57 USD / año',
      'legalNotice':
          'Esta herramienta tiene fines educativos y de apoyo. No reemplaza la evaluación de un profesional de la salud. Verifica siempre la información con fuentes oficiales.',
      'loginWelcome': 'Bienvenido a FarmaDose',
      'loginSubtitle':
          'Accede a tu cuenta para analizar medicamentos con apoyo de IA, fuentes oficiales y cálculos detallados.',
      'email': 'Correo electrónico',
      'emailHint': 'tucorreo@clinica.com',
      'password': 'Contraseña',
      'enter': 'Ingresar',
      'createAccount': 'Crear una cuenta',
      'forgotPassword': '¿Olvidaste tu contraseña?',
      'fillAllFields': 'Completa todos los campos.',
      'completeThisField': 'Completa este campo.',
      'invalidEmail': 'Correo electrónico inválido.',
      'invalidCredentials': 'Correo o contraseña inválidos.',
      'loginError': 'Error al iniciar sesión.',
      'passwordMinLength': 'La contraseña debe tener al menos 6 caracteres.',
      'passwordResetSent':
          'Te enviamos un enlace para restablecer tu contraseña.',
      'passwordRecoveryError':
          'No pudimos iniciar la recuperación de contraseña.',
      'noAccessSystem': 'No tienes acceso al sistema. Primero debes activar un plan.',
      'noActiveSubscription':
          'No encontramos una suscripción activa para este correo. Para acceder, primero debes elegir un plan.',
      'seePlans': 'Ver planes',
      'registerTitle': 'Crear cuenta',
      'registerSubtitle':
          'Registra a un profesional para acceder al flujo de análisis de medicamentos de FarmaDose.',
      'confirmPassword': 'Confirmar contraseña',
      'passwordsDoNotMatch': 'Las contraseñas no coinciden.',
      'createAccountSuccess': 'Cuenta creada correctamente.',
      'createAccountError': 'No se pudo crear la cuenta.',
      'emailAlreadyRegistered': 'Este correo ya está registrado.',
      'greeting': 'Hola, {email}',
      'homeSubtitle':
          'Gestiona tus análisis de medicamentos con fuentes oficiales, cálculos detallados y explicaciones claras para apoyar tu estudio o práctica clínica.',
      'newAnalysis': 'Nuevo análisis',
      'newAnalysisDescription':
          'Ingresa los datos principales para revisar dosis, fuentes oficiales y explicaciones claras.',
      'startAnalysis': 'Iniciar análisis',
      'history': 'Historial',
      'historyDescription':
          'Consulta tus análisis anteriores y revisa nuevamente cada resultado cuando lo necesites.',
      'viewHistory': 'Ver historial',
      'settings': 'Configuración',
      'settingsDescription':
          'Revisa tu correo, tu acceso actual y actualiza tu contraseña desde un solo lugar.',
      'openSettings': 'Abrir configuración',
      'logout': 'Cerrar sesión',
      'analysisTitle': 'Análisis de medicamentos',
      'analysisSubtitle':
          'Ingresa los datos necesarios para calcular, explicar y verificar la información con fuentes oficiales.',
      'medicationOrActiveIngredient': 'Medicamento o principio activo',
      'medicationHint': 'Ej.: amoxicilina',
      'age': 'Edad',
      'ageHint': 'Ej.: 8 años',
      'weightKg': 'Peso (kg)',
      'weightHint': 'Ej.: 24.5',
      'sex': 'Sexo',
      'countryOrPreferredSource': 'País o fuente preferida',
      'countryBrazil': 'Brasil',
      'countryMexico': 'México',
      'countryArgentina': 'Argentina',
      'countryColombia': 'Colombia',
      'countryChile': 'Chile',
      'countryPeru': 'Perú',
      'countryUnitedStates': 'Estados Unidos',
      'countryEurope': 'Europa',
      'countryOther': 'Otro',
      'male': 'Masculino',
      'female': 'Femenino',
      'other': 'Otro',
      'preferNotToSay': 'No informar',
      'analyzeMedication': 'Analizar medicamento',
      'analyzingMedication': 'Analizando medicamento...',
      'loadingStep1': 'Buscando fuentes oficiales...',
      'loadingStep2': 'Verificando información del medicamento...',
      'loadingStep3': 'Analizando dosis y seguridad...',
      'loadingStep4': 'Preparando explicación detallada...',
      'selectOption': 'Selecciona una opción.',
      'sourceRequired': 'Fuente requerida',
      'result': 'Resultado',
      'suggestions': 'Sugerencias',
      'medicationNotFoundTitle':
          'No encontramos este medicamento en fuentes oficiales confiables.',
      'medicationNotFoundHint':
          'Verifica si el nombre fue escrito correctamente o intenta buscar por el principio activo.',
      'noSuggestionsFound': 'No se encontraron sugerencias.',
      'sourceRequiredMessage':
          'Encontramos el medicamento, pero no encontramos una fuente oficial válida para el análisis.',
      'tryAnotherCountryOrSource': 'Intentar con otro país o fuente',
      'noAlternativeSources':
          'No encontramos fuentes alternativas disponibles en este momento.',
      'noSourceCountryTitle':
          'No encontramos una fuente oficial para el país seleccionado',
      'noSourceCountryMessage':
          'Puedes elegir otra fuente oficial disponible para continuar el análisis.',
      'selectOfficialSource': 'Selecciona una fuente oficial',
      'useThisSource': 'Usar esta fuente',
      'analysisSummary': 'Resumen del análisis',
      'useAndIndications': 'Uso e indicaciones',
      'therapeuticClass': 'Clase terapéutica',
      'whatIsItUsedFor': 'Para qué se utiliza',
      'commonSituations': 'Situaciones o síntomas comunes',
      'commonUses': 'Usos comunes',
      'mechanismSummary': 'Mecanismo resumido',
      'doseResult': 'Resultado de dosis',
      'officialDoseCalculated': 'Dosis oficial calculada',
      'estimatedDoseByAi': 'Dosis estimada por IA',
      'basedOnOfficialSource': 'Basado en la fuente oficial seleccionada.',
      'estimatedEducationalNotice':
          'Esta es una estimación educativa basada en literatura clínica y debe ser validada por un profesional de salud.',
      'frequency': 'Frecuencia',
      'duration': 'Duración',
      'maxDailyDose': 'Dosis máxima diaria',
      'estimatedFrequency': 'Frecuencia estimada',
      'estimatedDuration': 'Duración estimada',
      'educationalEstimate': 'Estimación educativa',
      'highConfidence': 'Confianza Alta',
      'mediumConfidence': 'Confianza Media',
      'lowConfidence': 'Confianza Baja',
      'unsafeDoseTitle': 'No fue posible calcular una dosis segura',
      'unsafeDoseMessage':
          'La fuente oficial no proporcionó datos suficientes y no se encontró una estimación clínica segura.',
      'stepByStepCalculation': 'Cálculo paso a paso',
      'calculationNotReceived': 'No se recibió un cálculo detallado.',
      'explanation': 'Explicación',
      'importantWarnings': 'Advertencias importantes',
      'warningsNotReceived': 'No se recibieron alertas importantes.',
      'officialSource': 'Fuente oficial',
      'noOfficialSourceReceived':
          'No se recibió una fuente oficial para este resultado.',
      'authority': 'Autoridad',
      'country': 'País',
      'title': 'Título',
      'openOfficialSource': 'Abrir fuente oficial',
      'aiClinicalSources': 'Fuentes clínicas usadas por la IA',
      'openSource': 'Abrir fuente',
      'educationalNotice': 'Aviso educativo',
      'pillCapsule': 'Tableta / cápsula',
      'liquidDrops': 'Líquido / gotas',
      'topical': 'Tópico',
      'injectable': 'Inyectable',
      'medicine': 'Medicamento',
      'doseAvailable': 'Dosis disponible',
      'estimateAvailable': 'Estimación disponible',
      'clinicalSource': 'Fuente clínica',
      'professional': 'profesional',
      'sessionExpired': 'Tu sesión no está disponible. Inicia sesión nuevamente.',
      'analysisRequestError':
          'No pudimos completar el análisis en este momento.',
      'historyTitle': 'Historial',
      'historyEmpty': 'Aún no tienes análisis guardados.',
      'historyLoadError': 'No pudimos cargar el historial en este momento.',
      'date': 'Fecha',
      'countryOrSource': 'País o fuente',
      'calculatedDoseResult': 'Resultado: dosis calculada',
      'estimatedDoseResult': 'Resultado: dosis estimada',
      'infoForReviewResult': 'Resultado: información disponible para revisión',
      'viewAnalysis': 'Ver análisis',
      'analysisDetail': 'Detalle del análisis',
      'account': 'Cuenta',
      'emailLabel': 'Correo',
      'plan': 'Plan',
      'status': 'Estado',
      'validity': 'Vigencia',
      'changePassword': 'Cambiar contraseña',
      'newPassword': 'Nueva contraseña',
      'saveNewPassword': 'Guardar nueva contraseña',
      'passwordUpdated': 'Contraseña actualizada correctamente.',
      'passwordUpdateError': 'No pudimos actualizar la contraseña.',
      'monthlyPlanLabel': 'Plan mensual',
      'annualPlanLabel': 'Plan anual',
      'planNotSpecified': 'Plan no especificado',
      'active': 'Activo',
      'canceledActiveAccess': 'Cancelado con acceso vigente',
      'refunded': 'Reembolsado',
      'chargeback': 'Pago revertido',
      'inactive': 'Inactivo',
      'noPlan': 'Sin plan',
      'notAvailable': 'No disponible',
      'noExpirationDate': 'Sin fecha de vencimiento',
      'adminAccess': 'Acceso administrativo',
      'accessSettingsTitle': 'Configuración',
      'brandSupportSubtitle':
          'Accede a tu cuenta para analizar medicamentos con apoyo de IA, fuentes oficiales y cálculos detallados.',
    },
    AppLanguage.portugueseBrazil: {
      'appName': 'FarmaDose',
      'language': 'Idioma',
      'spanishLatam': 'Español LATAM',
      'portugueseBrazil': 'Português Brasil',
      'loading': 'Carregando...',
      'close': 'Fechar',
      'save': 'Salvar',
      'landingBadge': 'Assinatura médica para LATAM',
      'landingHeadline': 'FarmaDose',
      'landingSubtitle':
          'Calcula, analisa e verifica doses de medicamentos com apoio de IA, fontes oficiais e explicação detalhada.',
      'startNow': 'Começar agora',
      'login': 'Entrar',
      'landingHeroTitle': 'Pensado para decisões mais claras e seguras',
      'landingHeroStat1Title': 'IA + critério clínico',
      'landingHeroStat1Description':
          'Explicações úteis em português para equipes do Brasil e LATAM.',
      'landingHeroStat2Title': 'Fontes verificáveis',
      'landingHeroStat2Description':
          'Consulte a base oficial selecionada antes de decidir.',
      'landingHeroStat3Title': 'Alertas automáticos',
      'landingHeroStat3Description':
          'Identifique inconsistências e erros potenciais em instantes.',
      'benefits': 'Benefícios',
      'benefit1': 'Cálculo detalhado passo a passo',
      'benefit2': 'Fontes oficiais verificáveis',
      'benefit3': 'Sugestões inteligentes se você digitar o medicamento errado',
      'benefit4': 'Alertas automáticos de segurança',
      'benefit5': 'Explicações em português para o Brasil',
      'howItWorks': 'Como funciona',
      'step1': 'Informe o medicamento',
      'step2': 'Adicione os dados do paciente',
      'step3': 'Selecione a fonte oficial',
      'step4': 'Revise o cálculo e a explicação',
      'plans': 'Planos',
      'monthlyPlan': 'Plano mensal',
      'annualPlan': 'Plano anual',
      'bestPrice': 'Melhor preço',
      'fullAccess': 'Acesso completo',
      'updatesIncluded': 'Atualizações incluídas',
      'chooseMonthlyPlan': 'Escolher plano mensal',
      'chooseAnnualPlan': 'Escolher plano anual',
      'monthlyPriceLabel': '\$6.90 USD / mês',
      'annualPriceLabel': '\$57 USD / ano',
      'legalNotice':
          'Esta ferramenta tem fins educacionais e de apoio. Não substitui a avaliação de um profissional de saúde. Sempre verifique as informações em fontes oficiais.',
      'loginWelcome': 'Bem-vindo ao FarmaDose',
      'loginSubtitle':
          'Acesse sua conta para analisar medicamentos com apoio de IA, fontes oficiais e cálculos detalhados.',
      'email': 'E-mail',
      'emailHint': 'seuemail@clinica.com',
      'password': 'Senha',
      'enter': 'Entrar',
      'createAccount': 'Criar uma conta',
      'forgotPassword': 'Esqueceu sua senha?',
      'fillAllFields': 'Preencha todos os campos.',
      'completeThisField': 'Preencha este campo.',
      'invalidEmail': 'E-mail inválido.',
      'invalidCredentials': 'E-mail ou senha inválidos.',
      'loginError': 'Erro ao entrar.',
      'passwordMinLength': 'A senha deve ter pelo menos 6 caracteres.',
      'passwordResetSent':
          'Enviamos um link para redefinir sua senha.',
      'passwordRecoveryError':
          'Não foi possível iniciar a recuperação de senha.',
      'noAccessSystem': 'Você não tem acesso ao sistema. Primeiro ative um plano.',
      'noActiveSubscription':
          'Não encontramos uma assinatura ativa para este e-mail. Para acessar, primeiro você precisa escolher um plano.',
      'seePlans': 'Ver planos',
      'registerTitle': 'Criar conta',
      'registerSubtitle':
          'Cadastre um profissional para acessar o fluxo de análise de medicamentos do FarmaDose.',
      'confirmPassword': 'Confirmar senha',
      'passwordsDoNotMatch': 'As senhas não coincidem.',
      'createAccountSuccess': 'Conta criada corretamente.',
      'createAccountError': 'Não foi possível criar a conta.',
      'emailAlreadyRegistered': 'Este e-mail já está cadastrado.',
      'greeting': 'Olá, {email}',
      'homeSubtitle':
          'Gerencie suas análises de medicamentos com fontes oficiais, cálculos detalhados e explicações claras para apoiar seu estudo ou prática clínica.',
      'newAnalysis': 'Nova análise',
      'newAnalysisDescription':
          'Informe os dados principais para revisar doses, fontes oficiais e explicações claras.',
      'startAnalysis': 'Iniciar análise',
      'history': 'Histórico',
      'historyDescription':
          'Consulte suas análises anteriores e revise novamente cada resultado quando precisar.',
      'viewHistory': 'Ver histórico',
      'settings': 'Configurações',
      'settingsDescription':
          'Veja seu e-mail, seu acesso atual e atualize sua senha em um só lugar.',
      'openSettings': 'Abrir configurações',
      'logout': 'Sair',
      'analysisTitle': 'Análise de medicamentos',
      'analysisSubtitle':
          'Informe os dados necessários para calcular, explicar e verificar as informações com fontes oficiais.',
      'medicationOrActiveIngredient': 'Medicamento ou princípio ativo',
      'medicationHint': 'Ex.: amoxicilina',
      'age': 'Idade',
      'ageHint': 'Ex.: 8 anos',
      'weightKg': 'Peso (kg)',
      'weightHint': 'Ex.: 24.5',
      'sex': 'Sexo',
      'countryOrPreferredSource': 'País ou fonte preferida',
      'countryBrazil': 'Brasil',
      'countryMexico': 'México',
      'countryArgentina': 'Argentina',
      'countryColombia': 'Colômbia',
      'countryChile': 'Chile',
      'countryPeru': 'Peru',
      'countryUnitedStates': 'Estados Unidos',
      'countryEurope': 'Europa',
      'countryOther': 'Outro',
      'male': 'Masculino',
      'female': 'Feminino',
      'other': 'Outro',
      'preferNotToSay': 'Não informar',
      'analyzeMedication': 'Analisar medicamento',
      'analyzingMedication': 'Analisando medicamento...',
      'loadingStep1': 'Buscando fontes oficiais...',
      'loadingStep2': 'Verificando informações do medicamento...',
      'loadingStep3': 'Analisando dose e segurança...',
      'loadingStep4': 'Preparando explicação detalhada...',
      'selectOption': 'Selecione uma opção.',
      'sourceRequired': 'Fonte obrigatória',
      'result': 'Resultado',
      'suggestions': 'Sugestões',
      'medicationNotFoundTitle':
          'Não encontramos esse medicamento em fontes oficiais confiáveis.',
      'medicationNotFoundHint':
          'Verifique se o nome foi digitado corretamente ou tente buscar pelo princípio ativo.',
      'noSuggestionsFound': 'Nenhuma sugestão encontrada.',
      'sourceRequiredMessage':
          'Encontramos o medicamento, mas não encontramos uma fonte oficial válida para análise.',
      'tryAnotherCountryOrSource': 'Tentar outro país/fonte',
      'noAlternativeSources':
          'Não encontramos fontes alternativas disponíveis neste momento.',
      'noSourceCountryTitle':
          'Não encontramos uma fonte oficial para o país selecionado',
      'noSourceCountryMessage':
          'Você pode escolher outra fonte oficial disponível para continuar a análise.',
      'selectOfficialSource': 'Selecione uma fonte oficial',
      'useThisSource': 'Usar esta fonte',
      'analysisSummary': 'Resumo da análise',
      'useAndIndications': 'Uso e indicações',
      'therapeuticClass': 'Classe terapêutica',
      'whatIsItUsedFor': 'Para que é utilizado',
      'commonSituations': 'Situações ou sintomas comuns',
      'commonUses': 'Usos comuns',
      'mechanismSummary': 'Mecanismo resumido',
      'doseResult': 'Resultado da dose',
      'officialDoseCalculated': 'Dose oficial calculada',
      'estimatedDoseByAi': 'Dose estimada por IA',
      'basedOnOfficialSource': 'Baseado na fonte oficial selecionada.',
      'estimatedEducationalNotice':
          'Esta é uma estimativa educacional baseada em literatura clínica e deve ser validada por um profissional de saúde.',
      'frequency': 'Frequência',
      'duration': 'Duração',
      'maxDailyDose': 'Dose máxima diária',
      'estimatedFrequency': 'Frequência estimada',
      'estimatedDuration': 'Duração estimada',
      'educationalEstimate': 'Estimativa educacional',
      'highConfidence': 'Confiança Alta',
      'mediumConfidence': 'Confiança Média',
      'lowConfidence': 'Confiança Baixa',
      'unsafeDoseTitle': 'Não foi possível calcular uma dose segura',
      'unsafeDoseMessage':
          'A fonte oficial não forneceu dados suficientes e não foi encontrada uma estimativa clínica segura.',
      'stepByStepCalculation': 'Cálculo passo a passo',
      'calculationNotReceived': 'Não foi recebido um cálculo detalhado.',
      'explanation': 'Explicação',
      'importantWarnings': 'Alertas importantes',
      'warningsNotReceived': 'Não foram recebidos alertas importantes.',
      'officialSource': 'Fonte oficial',
      'noOfficialSourceReceived':
          'Não foi recebida uma fonte oficial para este resultado.',
      'authority': 'Autoridade',
      'country': 'País',
      'title': 'Título',
      'openOfficialSource': 'Abrir fonte oficial',
      'aiClinicalSources': 'Fontes clínicas usadas pela IA',
      'openSource': 'Abrir fonte',
      'educationalNotice': 'Aviso educativo',
      'pillCapsule': 'Comprimido / cápsula',
      'liquidDrops': 'Líquido / gotas',
      'topical': 'Tópico',
      'injectable': 'Injetável',
      'medicine': 'Medicamento',
      'doseAvailable': 'Dose disponível',
      'estimateAvailable': 'Estimativa disponível',
      'clinicalSource': 'Fonte clínica',
      'professional': 'profissional',
      'sessionExpired': 'Sua sessão não está disponível. Entre novamente.',
      'analysisRequestError':
          'Não foi possível concluir a análise neste momento.',
      'historyTitle': 'Histórico',
      'historyEmpty': 'Você ainda não tem análises salvas.',
      'historyLoadError': 'Não foi possível carregar o histórico neste momento.',
      'date': 'Data',
      'countryOrSource': 'País ou fonte',
      'calculatedDoseResult': 'Resultado: dose calculada',
      'estimatedDoseResult': 'Resultado: dose estimada',
      'infoForReviewResult': 'Resultado: informação disponível para revisão',
      'viewAnalysis': 'Ver análise',
      'analysisDetail': 'Detalhe da análise',
      'account': 'Conta',
      'emailLabel': 'E-mail',
      'plan': 'Plano',
      'status': 'Status',
      'validity': 'Vigência',
      'changePassword': 'Alterar senha',
      'newPassword': 'Nova senha',
      'saveNewPassword': 'Salvar nova senha',
      'passwordUpdated': 'Senha atualizada corretamente.',
      'passwordUpdateError': 'Não foi possível atualizar a senha.',
      'monthlyPlanLabel': 'Plano mensal',
      'annualPlanLabel': 'Plano anual',
      'planNotSpecified': 'Plano não especificado',
      'active': 'Ativo',
      'canceledActiveAccess': 'Cancelado com acesso vigente',
      'refunded': 'Reembolsado',
      'chargeback': 'Pagamento contestado',
      'inactive': 'Inativo',
      'noPlan': 'Sem plano',
      'notAvailable': 'Não disponível',
      'noExpirationDate': 'Sem data de vencimento',
      'adminAccess': 'Acesso administrativo',
      'accessSettingsTitle': 'Configurações',
      'brandSupportSubtitle':
          'Acesse sua conta para analisar medicamentos com apoio de IA, fontes oficiais e cálculos detalhados.',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    var value = _values[language]?[key] ?? key;
    params?.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }
}

extension AppStringsContextExtension on BuildContext {
  LocaleService get localeService => LocaleScope.of(this);
  AppStrings get strings => AppStrings.of(localeService.language);
}
